files:
  include:
    - 'scss/**/*.scss'
    - 'website/src/**/*.scss'
rules:
  extends-before-mixins: 2
  extends-before-declarations: 2
  placeholder-in-extend: 2
  mixins-before-declarations: 2
  no-warn: 2
  no-debug: 2
  no-ids: 2
  no-css-comments: 0
  no-important: 2
  indentation:
    - 2
    -
      size: 4
  clean-import-paths: 0
  empty-line-between-blocks: 2
  force-pseudo-nesting: 0
  class-name-format:
    - 2
    -
      allow-leading-underscore: true
      convention: hyphenatedbem
  no-color-literals:
    - 2
    -
      allow-rgba: true
  hex-notation: 2
  border-zero: 2
  property-sort-order: 2
  quotes:
  - 2
  -
    style: single
  leading-zero: 0
  no-trailing-zero: 2
  single-line-per-selector: 2
  pseudo-element: 0
  attribute-quotes: 2
  trailing-semicolon: 2
  force-attribute-nesting: 2
  zero-unit: 2
  nesting-depth: 0
